In [2]:
""" Import packages """
import sys
import logging
import warnings

import numpy as np
import pandas as pd

sys.path.insert(0, '../scripts/')

warnings.filterwarnings("ignore")

In [3]:
from explorer import DataTransformer

transformer = DataTransformer()

In [4]:
REPO = "./"
filepath = "../data/cleaned/final/cleaned_project_dataset.csv"
rev = "clpdat3"

In [5]:
data = transformer.load_data(ext="csv", filepath=filepath, repo=REPO, rev=rev, header=0, parse_dates=["Date"])
data.head()

,Country,ISO3,Date,Target_1,Target_2,Target_3,Feature_1,Feature_2,Feature_3,Feature_4,...,Feature_23,Feature_24,Feature_25,Feature_26,Feature_27,Feature_28,Feature_29,Feature_30,Feature_31,Feature_32
0,Burkina Faso,BFA,2000-12-31,603.21100,874.85,249.82,2.55,43.4316,15.4232,3.020,...,714.73,29.06,22.72,0,0,0,0.0,2565.5260,0.0,0.0
1,Burkina Faso,BFA,2001-12-31,601.93774,918.92,264.60,2.97,44.7725,15.5302,3.060,...,749.26,29.19,22.77,0,0,0,0.0,2636.0425,0.0,0.0
2,Burkina Faso,BFA,2002-12-31,595.85205,958.85,274.54,2.90,46.1706,15.6492,3.089,...,690.37,29.47,23.24,0,0,0,0.0,2707.4575,0.0,0.0
3,Burkina Faso,BFA,2003-12-31,585.12330,965.41,278.27,2.60,47.6264,15.7656,3.120,...,935.59,29.34,23.12,0,0,0,0.0,2783.3055,0.0,0.0
4,Burkina Faso,BFA,2004-12-31,562.41130,925.19,267.83,3.00,49.1447,15.8710,3.156,...,752.75,29.41,23.25,0,0,0,0.0,2865.9350,0.0,0.0

In [6]:
data.groupby("Country")["Target_1"].describe()

,count,mean,std,min,25%,50%,75%,max
Country,,,,,,,,
Burkina Faso,23.0,491.800555,89.368271,366.081480,386.277750,526.309600,566.850250,603.211000
Chad,23.0,216.898296,22.105368,188.709730,202.102380,217.642470,227.800315,268.382450
Cote d'Ivoire,23.0,392.779503,112.791056,247.735570,277.085669,466.612030,485.665420,523.078100
Democratic Republic of Congo,23.0,386.051658,74.188404,295.763550,319.821880,365.719060,469.678940,481.689060
Ethiopia,23.0,135.166328,64.292154,34.707653,79.667503,141.754000,183.092515,231.740750
Ghana,23.0,302.019301,92.007139,149.486952,219.186990,336.385350,368.483235,435.234740
Kenya,23.0,100.709015,64.507781,45.101983,62.655340,68.770520,120.015615,241.661360
Madagascar,23.0,66.701654,37.302155,22.754910,42.582182,57.461670,71.191767,164.491509
Malawi,23.0,318.241757,86.288651,205.872440,226.650795,348.560850,374.595315,465.235630
Mali,23.0,397.014747,30.717527,333.695430,381.331085,391.829300,420.133575,452.815950
Mozambique,23.0,381.789569,62.981875,303.982850,334.835880,368.025630,405.369095,501.871370
Niger,23.0,356.049559,44.423788,294.673550,322.258336,352.145870,395.741425,429.718600
Nigeria,23.0,353.339069,50.441099,292.542420,303.205715,350.502350,404.457750,418.038640
Rwanda,23.0,226.162919,158.618506,37.947960,121.128985,190.429610,265.223278,724.567400
Senegal,23.0,98.235012,79.249423,32.890957,48.695842,60.474945,123.266680,306.242220
Sierra Leone,23.0,404.836832,46.697583,317.947171,377.926350,408.435100,442.693660,473.005340
Tanzania,23.0,180.567699,76.507093,109.748547,124.104830,140.304300,237.545665,339.933500
Togo,23.0,351.833873,85.918055,216.153395,295.206300,352.471530,443.158645,465.799040
Uganda,23.0,371.196457,87.337809,253.514790,283.477345,394.679720,428.348315,507.974400
Zambia,23.0,232.696871,76.786292,165.219040,179.675815,200.348590,245.383465,404.154000
Zimbabwe,23.0,98.752055,26.174220,55.826330,78.338670,103.266717,113.032805,175.120470

In [7]:
data.groupby("Country")["Target_2"].describe()

,count,mean,std,min,25%,50%,75%,max
Country,,,,,,,,
Burkina Faso,23.0,713.493971,214.688493,366.793356,490.835000,825.550000,864.870,965.41
Chad,23.0,183.703659,47.674646,123.105478,140.445000,188.700000,219.525,288.58
Cote d'Ivoire,23.0,518.055658,146.681011,324.918255,379.170000,541.680000,658.835,697.02
Democratic Republic of Congo,23.0,571.771082,212.326930,284.200062,379.490000,566.050000,786.150,848.04
Ethiopia,23.0,118.297978,62.516406,40.330000,67.914349,106.990000,161.590,267.24
Ghana,23.0,393.240365,104.166565,235.667734,284.220000,422.180000,483.475,527.70
Kenya,23.0,88.893825,52.952310,18.960000,53.330000,71.180425,119.775,185.83
Madagascar,23.0,108.342316,44.472049,67.901198,73.380000,81.610000,155.880,191.24
Malawi,23.0,261.465444,118.468203,131.333658,156.070000,220.590000,329.330,525.74
Mali,23.0,644.673264,205.118871,317.265612,406.285000,742.410000,796.375,859.89
Mozambique,23.0,312.634869,135.789529,150.502275,182.970000,286.930000,401.455,561.71
Niger,23.0,517.847423,119.754160,318.491248,448.705000,533.940000,609.055,682.56
Nigeria,23.0,481.895539,149.080617,256.323451,309.230000,533.780000,610.945,644.21
Rwanda,23.0,195.548493,126.602612,108.080000,118.342086,146.810000,182.385,522.66
Senegal,23.0,190.402237,120.844448,79.943481,100.310000,177.100000,235.065,629.66
Sierra Leone,23.0,829.018117,223.671254,481.896069,641.295000,882.510000,1037.325,1100.43
Tanzania,23.0,233.723384,125.470699,122.626357,144.835000,182.910000,288.435,498.64
Togo,23.0,262.391911,76.374151,155.221125,184.670000,252.340000,332.810,373.68
Uganda,23.0,492.016594,252.555539,208.584199,259.295000,441.200000,695.330,898.92
Zambia,23.0,138.398359,65.681819,76.641537,92.940000,109.820000,154.025,279.98
Zimbabwe,23.0,96.895382,33.316490,53.115514,58.145000,99.430000,127.755,148.46

In [8]:
data.groupby("Country")["Target_3"].describe()

,count,mean,std,min,25%,50%,75%,max
Country,,,,,,,,
Burkina Faso,23.0,204.903550,63.026180,104.927485,137.450000,237.040000,249.645,278.27
Chad,23.0,57.434948,13.612539,40.202470,44.670000,59.180000,67.750,85.82
Cote d'Ivoire,23.0,156.834415,40.229039,106.505228,115.650000,167.540000,195.980,209.02
Democratic Republic of Congo,23.0,121.011118,47.034609,56.912985,78.295000,121.370000,168.980,180.26
Ethiopia,23.0,22.588282,12.651632,7.260000,12.126048,19.880000,31.145,52.45
Ghana,23.0,106.859603,29.414631,63.772674,73.195000,119.090000,133.160,139.58
Kenya,23.0,21.237614,13.978939,4.020000,11.710000,15.809008,29.900,47.22
Madagascar,23.0,33.062565,13.832260,20.607348,22.155000,24.580000,47.270,58.70
Malawi,23.0,69.858130,33.547958,32.405402,39.110000,56.950000,92.935,139.53
Mali,23.0,155.140698,50.955361,74.578929,95.415000,176.010000,191.840,209.55
Mozambique,23.0,110.237577,38.099761,61.384597,73.650000,108.160000,133.630,177.85
Niger,23.0,152.172556,34.797780,96.230110,130.080000,156.610000,176.605,201.46
Nigeria,23.0,136.288031,38.591713,81.519555,91.790000,147.790000,172.830,178.39
Rwanda,23.0,44.298884,32.646086,22.626359,25.071959,31.840000,39.680,132.47
Senegal,23.0,71.634355,35.894020,37.750000,46.310000,71.680000,86.290,205.47
Sierra Leone,23.0,226.010220,65.498025,128.999575,169.280000,233.170000,285.605,306.26
Tanzania,23.0,50.825144,29.286009,25.307436,30.395000,38.880000,62.565,114.18
Togo,23.0,91.036837,17.549779,66.262860,73.100000,92.840000,103.380,118.46
Uganda,23.0,119.556602,67.105195,45.920164,58.075000,104.970000,171.645,229.75
Zambia,23.0,43.314152,22.752482,22.355174,27.775000,33.850000,48.245,92.73
Zimbabwe,23.0,29.985802,14.537724,12.212747,14.445000,26.610000,44.545,51.12